[package]
name = "bitcoin-types"
version = "0.1.0"
authors = ["Olga Kuniavskaia <olga.kuniavskaia@nearone.org>"]
edition = "2021"
publish = false

[dependencies]
near-sdk.workspace = true
near-contract-standards.workspace = true
hex.workspace = true
borsh.workspace = true
serde.workspace = true
